#server {
 #   listen 80;
  #  server_name s1543278.smartape-vps.com www.s1543278.smartape-vps.com;
   # return 301 https://$host$request_uri;
#}

#server {
 #   listen 443 ssl;
  #  server_name s1543278.smartape-vps.com www.s1543278.smartape-vps.com;

   # ssl_certificate /etc/letsencrypt/live/s1543278.smartape-vps.com/fullchain.pem;
    #ssl_certificate_key /etc/letsencrypt/live/s1543278.smartape-vps.com/privkey.pem;

    #location / {
   #     proxy_pass http://frontend:80;
    #}
#}

server {
    listen 80;
    server_name твой-домен.com www.твой-домен.com;

    location / {
        proxy_pass http://frontend:80;
    }
}